service: serverless-cinebinge 

plugins:
  - serverless-webpack

mode: development

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs6.10

functions:
  forLocation:
    handler: lambda/list.forLocation
    events:
      - http:
          method: get
          path: list/for-location/{location}
          cors: true
