service: serverless-cinebinge 

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: true

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs6.10

functions:
  forLocation:
    handler: lambda/handler.forLocation
    events:
      - http:
          method: get
          path: list/for-location/{location}
          cors: true
